### ISSUE TITLE
Scheme key not found, Is it running failed tests only or entire scheme?

### ISSUE THREAD

**Issue by Shashikant86** [lyndsey-ferguson/fastlane_plugins#4]
Just tried to clone the repo and executing the test 

                      $ git clone git@github.com:lyndsey-ferguson/fastlane_plugins.git
                      $cd cd fastlane_plugins/fastlane-plugin-setup_fragile_tests_for_rescan/
                      $ bundle install 
                      $ fastlane install_plugins
                      $ bundle exec fastlane test

I got an error that 'Scheme" key doesn't found. I can't see the option is set anywhere. Error is 
` (master)>──» bundle exec fastlane test                                       0 < 08:15:28
+------------------------------------------------+---------+--------------------------------+
|                                       Used plugins                                        |
+------------------------------------------------+---------+--------------------------------+
| Plugin                                         | Version | Action                         |
+------------------------------------------------+---------+--------------------------------+
| fastlane-plugin-setup_fragile_tests_for_rescan | 0.1.2   | setup_fragile_tests_for_rescan |
+------------------------------------------------+---------+--------------------------------+

[08:15:41]: Driving the lane 'test' 🚀
+---------------+------+
|     Lane Context     |
+---------------+------+
| PLATFORM_NAME |      |
| LANE_NAME     | test |
+---------------+------+
[08:15:41]: key not found: :scheme
[08:15:41]: fastlane finished with errors

`

I got another question here, is it re-scan only failed test or entire scheme ? If it creates new scheme based on the test failed then how to pass the scheme ?

If thats running entire test suite then we will end up running passing tests again which we don't want right ?

**Comment by lyndsey-ferguson** [comment]
Are you running my example Fastfile? If so, then you'll need to provide the scheme that will be tested. We have multiple schemes and I realize that some people only have the one: I can update the plugin, but for now, just provide your one scheme via the command line: `bundle exec fastlane test scheme:<insert_scheme_name_here>`.

**Comment by lyndsey-ferguson** [comment]
This plugin will modify the scheme to [skip](https://github.com/lyndsey-ferguson/fastlane_plugins/blob/master/fastlane-plugin-setup_fragile_tests_for_rescan/lib/fastlane/plugin/setup_fragile_tests_for_rescan/actions/setup_fragile_tests_for_rescan_action.rb#L32) the passing tests and re-run the scheme, which will then only run the failing tests. The idea is that this is run from a CI machine (like Jenkins or Travis) where you don't mind the scheme being modified.

**Comment by Shashikant86** [comment]
@lyndsey-ferguson Thanks for the clarification. So the we can explicitly pass the scheme in the `Fastfile` like 

                             scheme_to_test = "MyUITestScheme"
Right ? 

Sound great idea ! I will keep you posted how it goes :)
👍 Great Job !

**Comment by lyndsey-ferguson** [comment]
Yeah, get rid of the check for the scheme option and pass "MyUITestScheme" directly to this action

**Comment by Shashikant86** [comment]
@lyndsey-ferguson Sounds Great !  however I can't get that working, it seems to be running entire scheme/test suite again. 
I created a demo project [CoinTossing](https://github.com/Shashikant86/CoinTossing) and tried to execute that on Travis CI but it seems re-run entire things and build keep running forever 

The complete TravisCI output [here ](https://travis-ci.org/Shashikant86/CoinTossing/builds/191868255)

Let me know if I am missing something there in the main project config '[CoinTossing](https://github.com/Shashikant86/CoinTossing)'

**Comment by lyndsey-ferguson** [comment]
Thank you for providing the sample project. There is a difference between how the report is generated and how the test is suppressed. I have fixed the problem, added tests for this case, and updated the plugin to '0.2.0' for this new functionality. Please update and let me know if it works for you (it worked locally for me after my changes).

:fire

**Comment by Shashikant86** [comment]
Works Like a charm 👍 🍏

**Comment by lyndsey-ferguson** [comment]
Wonderful! Thanks for the quick feedback and help!
