### ISSUE TITLE
Rescan plugin aggregates test results

### ISSUE THREAD

**Issue by dyang** [lyndsey-ferguson/fastlane_plugins#5]
Hi,

Just wonder if there is a way to aggregate test results across all runs? 

Right now it seems that the final report.xml contains only the results of the very last run. What I'd love to have is a report of all test cases and their results, so that I can upload it on Jenkins. 

Thanks! :)

**Comment by lyndsey-ferguson** [comment]
Hi @dyang, each time `scan` is run, it generates a new xml report file. What you could do is rename the produced report xml to a tmp_0, tmp_1 xml file then put them together at the end. This plugin is really about the current result.

Does that help?

**Comment by dyang** [comment]
Thanks for the info. I'll look into it.

**Comment by lyndsey-ferguson** [comment]
@dyang if you do come up with something, I'd be happy to put it in the Fastfile example.

**Comment by dyang** [comment]
@lyndsey-ferguson How about this? https://github.com/dyang/merge_junit_report.  :)
It's still alpha quality. I'll keep tweaking it in the next few days. Please let me know how it works for you. :)

**Comment by lyndsey-ferguson** [comment]
Thanks, looking forward to it: I will be able to try it out next week
