### ISSUE TITLE
When using --includeOnly parameter the scheme skip settings are ignored

### ISSUE THREAD

**Issue by zaidkazi** [lyndsey-ferguson/fastlane_plugins#6]
Hi this plugin is great although i usually run subsets of my UITestScheme by using fastlane scans option --includeOnly what ive noticed is when you use that option on the retry failure portion it runs all tests the tests from that portion even the ones that were supressed because they passed.

**Comment by lyndsey-ferguson** [comment]
Hi, thanks for using the plugin (I'm guessing you mean the `fastlane-plugin-setup_fragile_tests_for_rescan`)! 

I cannot find the `--includeOnly` `scan` option. Can you include a snippet from your Fastfile outlining how you use it? 

The plugin works by adding the passing tests to the list of "skipped tests" for the Scheme so that when you re-run `scan` with the same Scheme, those tests are not run again, they are skipped, and only the failing tests are tested.

**Comment by zaidkazi** [comment]
Sure :D , ive attached a few things for you that should help clarify.

First here is a description of the scan option which you could find by using 'fastlane scan help' in terminal ive copied the option for you but its listed as  

>     --only_testing [VALUE] Array of strings matching Test Bundle/Test Suite/Test Cases to run (SCAN_ONLY_TESTING)

**Now here is how i use it in my fastfile** 

`lane :ciuitest do |options|
  scheme_to_test = options[:scheme]
  scan_options = {
    scheme: scheme_to_test,
    device: 'iPhone 7 Plus',
    output_directory: 'artifacts/tests',
    custom_report_file_name: 'report.xml',
    **_only_testing: 'UITestTargetName/AuthenticationTests'_**
    
   }
 begin
    retry_count ||= 0
    scan(scan_options)
  rescue => e
    UI.important("failure noted: #{e}")
    report_filepath = File.absolute_path('../artifacts/tests/report.xml')
    unless File.exist?(report_filepath)
      raise e
    end
    if (retry_count += 1) < 3
      setup_fragile_tests_for_rescan(
        project_path: File.absolute_path('../myproj.xcodeproj'),
        scheme: scheme_to_test,
        report_filepath: report_filepath
      )
      clear_derived_data
      retry
    end
  end
 end

`


_This allows to run only the tests that are part of the authentication class and ignore any other test classes that are part of that UITestTarget _

**Comment by zaidkazi** [comment]
One more thing ive noticed is that there is a scan option  

>  derived_data_path: 'myderiveddata'

which allows you to pass in a derived data option although the "clear_derived_data" option before the retry doesint reference it rather still goes to the deafult derived data folder.

**Comment by lyndsey-ferguson** [comment]
Ok. Here's the deal, you taught me something. That parameter actually gets translated to a command that `xcodebuild` uses. Using those parameters will completely override what is specified in the Scheme.

I could update the action to return an array of tests to suppress and you could either remove those elements from the `:only_testing` list that you're using? Or add them to the `:skip_testing` option that you've created. Thoughts?

See: http://stackoverflow.com/a/40558173/71877

**Comment by zaidkazi** [comment]
Awesome that sounds like it would work I think making use of the skip testing would be alot neater.

If the supressed tests returned an array of tests that could be passed as the value of the :skip_testing option i think that solved my problems 100% as long as the final report still gets modified correctly :D. 

Although can you please share a quick snippet of how i could use it once done :D. Much appreciated.

This gem is a life saver for me.

**Comment by lyndsey-ferguson** [comment]
I'll update the example with how it can be used and send you a link to it

**Comment by zaidkazi** [comment]
Thanks !

**Comment by lyndsey-ferguson** [comment]
@zaidkazi ok, I've released a new version that returns the list of tests to skip, check it out and let me know if it works for you; if so, we can close this issue.

**Comment by lyndsey-ferguson** [comment]
Oh, the snippet. 
```
begin  
  tests_to_skip = []
  scan(.., skip_testing: test_to_skip)
rescue => e
  tests_to_skip = setup_fragile_tests_for_rescan(...)
  retry if true # put in a counter
end
```

**Comment by lyndsey-ferguson** [comment]
I just realized that the plugin will only return the list of new tests that it suppressed. Maybe it should use the Scheme to provide a list of all tests that are suppressed (the previously suppressed ones too).

**Comment by zaidkazi** [comment]
forsure that sounds like a good idea

**Comment by zaidkazi** [comment]
Hey Lyndsey upon testing your new update i came to realize two things

You can only use one of the following  (only_testing or skip_testing) if only_testing is a test class

**Example only_testing: 'UITestTargetName/AuthenticationTests'**
Lets say authentication tests contain 3 tests 

After running the tests lets say we had the following outcome
- signinwithnumeric ✗
-signinwithspecialcharacters ✓
-signin40characters ✓

If tests_to_skip returns signinwithspecialcharacters and signin40characters 

then the next time the retry is called those should be added to the skip_testing array although there is a slight problem with this after running it i verified that using only_testing if it includes the entire test class takes priority over the skip_testing so all tests would end up re running.


The quickest solution i think at this point is for setup_fragile_tests_for_rescan to return a list of testcases that have failed so they could be passed back in to override the only_testing option array.

so in the above example after calling setup_fragile_tests_for_rescan it would return back signinwithnumeric and that could be passed back into only_testing.

**Comment by lyndsey-ferguson** [comment]
Ah, ok, so you are saying that if I pass in to `scan`:

```ruby
scan(
  only_testing: 'UITestTargetName/AuthenticationTests',
  skip_testing: 'UITestTargetName/AuthenticationTests/signinwithspecialcharacters, UITestTargetName/AuthenticationTests/signin40characters', 
  ...
)
```
`xcodebuild` will end up testing the entire `UITestTargetName/AuthenticationTests` class and what you're proposing is to return from `setup_fragile_tests_for_rescan` the tests that failed so that we call scan with:

```ruby
scan(
  only_testing: 'UITestTargetName/AuthenticationTests/signinwithnumeric',
  ...
)
```

That sounds good. I am considering prepending the bundle name in each string in addition to returning the failures. Sounds good?
1. make the list a

**Comment by zaidkazi** [comment]
Yes sir exactly :) I tested the solution manually yesterday and it worked ! 

Awesome thank you. Also yes I noticed two things yesterday I had to manually add the bundle name to each returned test and also had to chomp" () " the two bracket after each test name for it to work

**Comment by lyndsey-ferguson** [comment]
Ok, will remove the "()" after each test name too, thank you for helping!

**Comment by zaidkazi** [comment]
My pleasure :)

**Comment by lyndsey-ferguson** [comment]
@zaidkazi I released a new version. This one will break code that relied on getting a list of failed tests. The new plugin action now returns a hash with keys `:passed_tests` and `:failed_tests`. Each have an array of fully qualified tests, `bundle_name/class_name/test_name` (no `()`). Take a look and let me know how it works for you.

**Comment by zaidkazi** [comment]
Hey lyndsey it works great but i think the functionality for updating the  xml report in the rescan is broken? It seems to overwite the entire file with just the latest rescan results

**Comment by lyndsey-ferguson** [comment]
The plugin doesn't write to the xml report. `scan` itself would create its own test report and you'll have to give it a different name each time `scan` is invoked. For example:
```ruby
begin
  retry_count ||= 0
  UI.header("Scan #: #{retry_count + 1}")
  reports_list << "report_#{retry_count}.xml"
  scan_options[:custom_report_file_name] = reports_list.last
  scan(scan_options)
rescue => e
  report_filepath = File.absolute_path("../artifacts/tests/#{reports_list.last}")
  unless File.exist?(report_filepath)
    # something really broke, propagate the error out
    raise e
  end
  if (retry_count += 1) < 3
    setup_fragile_tests_for_rescan(
      project_path: 'MyApp/MyApp.xcodeproj'
      scheme: scan_options[:scheme],
      report_filepath: report_filepath
    )
    retry
  end
end
```

**Comment by zaidkazi** [comment]
Ah I see I thought it updated the existing junit files makes sense I think everything is good on my end then :) we can close the issue
